export const WEAPONS = {
  ak47: 'AK-47',
  bizon: 'PP-Bizon',
  cz75a: 'CZ75-Auto',
  deagle: 'Desert Eagle',
  decoy: 'Decoy Grenade',
  elite: 'Duel Berettas',
  fiveseven: 'Five-SeveN',
  flashbang: 'Flashbang',
  galil: 'Galil AR',
  glock: 'Glock',
  hegrenade: 'HE Grenade',
  hkp2000: 'P2000',
  incgrenade: 'Incendiary Grenade',
  inferno: 'Fire',
  knife: 'Knife',
  m4a1: 'M4A1-S',
  mac10: 'MAC-10',
  mag7: 'MAG-7',
  molotov: 'Molotov',
  negev: 'Negev',
  nova: 'Nova',
  revolver: 'R8 Revolver',
  sawedoff: 'Sawed Off',
  scar20: 'SCAR-20',
  sg556: 'SG 553',
  smokegrenade: 'Smoke Grenade',
  ssg08: 'SSG 08',
  taser: 'Zeus x27',
  tec9: 'Tec-9',
  ump45: 'UMP-45',
  mp5sd: 'MP5-SD',
  usp: 'USP-S',
};
