name: Build

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    # Rust
    - uses: Swatinem/rust-cache@v2
    - name: Build csdemoparser
      run: cargo build -p csdemoparser --release
    - name: Test csdemoparser
      run: cargo test -p csdemoparser --release
    # oldui
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'src/newui/package-lock.json'
    - run: npm install -g bower
    - run: bower install
    # newui
    - name: newui
      run: |
        cd src/newui
        npm install
        npm run build
        cp -R dist/spa/* ../../resources/public/
    # Clojure
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Install Leiningen
      uses: DeLaGuardo/setup-clojure@11.0
      with:
        lein: '2.10.0'
    - name: Cache Clojure dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: cljdeps-${{ hashFiles('project.clj') }}
        restore-keys: cljdeps-
    - name: Build jar
      run: LEIN_SNAPSHOTS_IN_RELEASE=1 lein uberjar
    - run: |
        mv target-lein/hsbox-*-standalone.jar target-lein/hsbox-standalone.jar
        echo 'java -jar hsbox-standalone.jar --port 4000' > target-lein/headshotbox.sh
        chmod a+x target-lein/headshotbox.sh
    # Package
    - name: Zip
      run: zip -j headshotbox.zip target-lein/hsbox-standalone.jar target-lein/headshotbox.sh target/release/csdemoparser
    - uses: actions/upload-artifact@v3
      with:
        name: headshotbox
        path: headshotbox.zip
